export interface Palette {
  id: number;
  name: string;
  colors: {
    bg: string;
    bgAlt: string;
    card: string;
    accent: string;
    accentLight: string;
    accentDark: string;
    text: string;
    textSecondary: string;
    button: string;
    buttonText: string;
  };
}

export const palettes: Palette[] = [
  {
    id: 1,
    name: "Весенняя поляна",
    colors: {
      bg: "#E0F0DC",
      bgAlt: "#D4E8D0",
      card: "#EDF7E8",
      accent: "#6BAA7C",
      accentLight: "#A4D4B4",
      accentDark: "#4E8E64",
      text: "#2A4A35",
      textSecondary: "#3F6A4A",
      button: "#5FA978",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 2,
    name: "Луговая зелень",
    colors: {
      bg: "#DCE8D4",
      bgAlt: "#D0DCCA",
      card: "#E9F2E4",
      accent: "#68A474",
      accentLight: "#9FCC9F",
      accentDark: "#4D885D",
      text: "#2A4833",
      textSecondary: "#3E6848",
      button: "#5C9F70",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 3,
    name: "Молодой папоротник",
    colors: {
      bg: "#E4F0D8",
      bgAlt: "#D8E4CC",
      card: "#F0F7E8",
      accent: "#7AB054",
      accentLight: "#AAD480",
      accentDark: "#5F9640",
      text: "#2E4A28",
      textSecondary: "#446A3C",
      button: "#70AA4E",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 4,
    name: "Лесной мох",
    colors: {
      bg: "#DEE6D8",
      bgAlt: "#D2DAD0",
      card: "#EAF0E6",
      accent: "#6A9E72",
      accentLight: "#9BC6A0",
      accentDark: "#52825A",
      text: "#2C4432",
      textSecondary: "#406448",
      button: "#60986A",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 5,
    name: "Липовая листва",
    colors: {
      bg: "#E6EED8",
      bgAlt: "#DAE2CC",
      card: "#F0F5E8",
      accent: "#7FB864",
      accentLight: "#AFDA90",
      accentDark: "#659C4A",
      text: "#304A28",
      textSecondary: "#486A3C",
      button: "#74B25C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 6,
    name: "Клевер",
    colors: {
      bg: "#DFF0DC",
      bgAlt: "#D3E4D0",
      card: "#ECF7E8",
      accent: "#6AAC76",
      accentLight: "#A0D0AA",
      accentDark: "#50905C",
      text: "#284A32",
      textSecondary: "#3C6A46",
      button: "#5EA670",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 7,
    name: "Шалфей",
    colors: {
      bg: "#DCE8E0",
      bgAlt: "#D0DCDA",
      card: "#E8F0EC",
      accent: "#6A9C88",
      accentLight: "#9EC4B4",
      accentDark: "#50806E",
      text: "#2A4A40",
      textSecondary: "#3E6A58",
      button: "#5E9680",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 8,
    name: "Петрушка",
    colors: {
      bg: "#E0F0DC",
      bgAlt: "#D4E4D0",
      card: "#EDF7E8",
      accent: "#6DB078",
      accentLight: "#A2D4AC",
      accentDark: "#52945E",
      text: "#2A4C34",
      textSecondary: "#3E6C48",
      button: "#61AA70",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 9,
    name: "Базилик",
    colors: {
      bg: "#DCEAE4",
      bgAlt: "#D0DEDA",
      card: "#E8F2EC",
      accent: "#5FA482",
      accentLight: "#93CAB0",
      accentDark: "#478868",
      text: "#2A4A3E",
      textSecondary: "#3E6A56",
      button: "#559E7C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 10,
    name: "Розмарин",
    colors: {
      bg: "#DCE8DC",
      bgAlt: "#D0DCD4",
      card: "#E8F0E8",
      accent: "#6AA078",
      accentLight: "#9FCAA8",
      accentDark: "#50845E",
      text: "#2A4A36",
      textSecondary: "#3E6A4A",
      button: "#5E9A70",
      buttonText: "#FFFFFF",
    },
  },

  {
    id: 11,
    name: "Тимьян",
    colors: {
      bg: "#E0EAD8",
      bgAlt: "#D4DECC",
      card: "#ECF2E4",
      accent: "#6E9E70",
      accentLight: "#A2C6A0",
      accentDark: "#548256",
      text: "#2C4A30",
      textSecondary: "#426A46",
      button: "#629868",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 12,
    name: "Мелисса",
    colors: {
      bg: "#E6F0DC",
      bgAlt: "#DAE4D0",
      card: "#F0F7E8",
      accent: "#78B060",
      accentLight: "#A8D48C",
      accentDark: "#5E9446",
      text: "#2E4C2A",
      textSecondary: "#446C3E",
      button: "#6CAA58",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 13,
    name: "Укроп",
    colors: {
      bg: "#DCE8E0",
      bgAlt: "#D0DCDA",
      card: "#E8F0EC",
      accent: "#649E88",
      accentLight: "#98C6B4",
      accentDark: "#4A826E",
      text: "#2A4A3E",
      textSecondary: "#3E6A56",
      button: "#5A9880",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 14,
    name: "Кориандр",
    colors: {
      bg: "#E0EEDC",
      bgAlt: "#D4E2D0",
      card: "#ECF5E8",
      accent: "#6CAE78",
      accentLight: "#A0D2AC",
      accentDark: "#52925E",
      text: "#2A4C34",
      textSecondary: "#3E6C48",
      button: "#60A870",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 15,
    name: "Руккола",
    colors: {
      bg: "#DCE8D8",
      bgAlt: "#D0DCCE",
      card: "#E8F0E4",
      accent: "#5E9A6E",
      accentLight: "#92C29E",
      accentDark: "#467E54",
      text: "#284A36",
      textSecondary: "#3C6A4A",
      button: "#549466",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 16,
    name: "Сосновая хвоя",
    colors: {
      bg: "#DCE8E4",
      bgAlt: "#D0DCDA",
      card: "#E8F0EC",
      accent: "#5C9C8A",
      accentLight: "#90C4B6",
      accentDark: "#448070",
      text: "#2A4A40",
      textSecondary: "#3E6A58",
      button: "#529682",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 17,
    name: "Ель",
    colors: {
      bg: "#DAEAE0",
      bgAlt: "#CEDEDC",
      card: "#E6F2EC",
      accent: "#58A080",
      accentLight: "#8CC8AE",
      accentDark: "#408466",
      text: "#284A3C",
      textSecondary: "#3C6A54",
      button: "#4E9A78",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 18,
    name: "Кедр",
    colors: {
      bg: "#DEE8DC",
      bgAlt: "#D2DCDA",
      card: "#EAF0E8",
      accent: "#629E7A",
      accentLight: "#96C6A8",
      accentDark: "#488260",
      text: "#2A4A38",
      textSecondary: "#3E6A4C",
      button: "#58986C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 19,
    name: "Можжевельник",
    colors: {
      bg: "#DCE6DC",
      bgAlt: "#D0DAD4",
      card: "#E8EEE8",
      accent: "#6A9A7C",
      accentLight: "#9EC2AA",
      accentDark: "#507E62",
      text: "#2C4A38",
      textSecondary: "#406A4C",
      button: "#5E9474",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 20,
    name: "Пихта",
    colors: {
      bg: "#DAE8E0",
      bgAlt: "#CEDCD8",
      card: "#E6F0EC",
      accent: "#5A9E82",
      accentLight: "#8EC6B0",
      accentDark: "#428268",
      text: "#2A4A3E",
      textSecondary: "#3E6A56",
      button: "#50987A",
      buttonText: "#FFFFFF",
    },
  },

  {
    id: 21,
    name: "Туя",
    colors: {
      bg: "#E4EEDC",
      bgAlt: "#D8E2D0",
      card: "#F0F5E8",
      accent: "#74AC68",
      accentLight: "#A6D096",
      accentDark: "#5A904E",
      text: "#2E4C2C",
      textSecondary: "#446C40",
      button: "#68A65C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 22,
    name: "Лиственница",
    colors: {
      bg: "#E0ECDC",
      bgAlt: "#D4E0D0",
      card: "#ECF4E8",
      accent: "#6CA870",
      accentLight: "#9ECAA0",
      accentDark: "#528C56",
      text: "#2A4C32",
      textSecondary: "#3E6C46",
      button: "#60A268",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 23,
    name: "Кипарис",
    colors: {
      bg: "#DCEADC",
      bgAlt: "#D0DEDA",
      card: "#E8F2E8",
      accent: "#629E7C",
      accentLight: "#96C6AA",
      accentDark: "#488262",
      text: "#2A4A38",
      textSecondary: "#3E6A4C",
      button: "#589870",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 24,
    name: "Тис",
    colors: {
      bg: "#DAE6DC",
      bgAlt: "#CEDAD8",
      card: "#E6EEE8",
      accent: "#5E9A78",
      accentLight: "#92C2A6",
      accentDark: "#447E5E",
      text: "#2A4A38",
      textSecondary: "#3E6A4C",
      button: "#549470",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 25,
    name: "Ягель",
    colors: {
      bg: "#DCE8DC",
      bgAlt: "#D0DCD6",
      card: "#E8F0E8",
      accent: "#689E7E",
      accentLight: "#9CC6AC",
      accentDark: "#4E8264",
      text: "#2C4A38",
      textSecondary: "#406A4C",
      button: "#5E9876",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 26,
    name: "Зелёный чай",
    colors: {
      bg: "#E8F0DC",
      bgAlt: "#DCE4D0",
      card: "#F2F7E8",
      accent: "#7EBC68",
      accentLight: "#AED896",
      accentDark: "#64A04E",
      text: "#304C2A",
      textSecondary: "#486C3E",
      button: "#72B65C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 27,
    name: "Матча",
    colors: {
      bg: "#E4F0D8",
      bgAlt: "#D8E4CC",
      card: "#F0F7E4",
      accent: "#78B65C",
      accentLight: "#A6DA88",
      accentDark: "#5E9A42",
      text: "#2E4C28",
      textSecondary: "#446C3C",
      button: "#6CB054",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 28,
    name: "Жасминовый чай",
    colors: {
      bg: "#E8F2DC",
      bgAlt: "#DCE6D0",
      card: "#F2F9E8",
      accent: "#7CBA64",
      accentLight: "#ACDC90",
      accentDark: "#629E4A",
      text: "#304E2A",
      textSecondary: "#486E3E",
      button: "#70B45C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 29,
    name: "Мятный чай",
    colors: {
      bg: "#DCF0E8",
      bgAlt: "#D0E4DC",
      card: "#E8F7F0",
      accent: "#64AE92",
      accentLight: "#94D4BE",
      accentDark: "#4A9278",
      text: "#2A4C40",
      textSecondary: "#3E6C58",
      button: "#5AA88A",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 30,
    name: "Бамбук",
    colors: {
      bg: "#E6F0DC",
      bgAlt: "#DAE4D0",
      card: "#F0F7E8",
      accent: "#7AB65C",
      accentLight: "#A8DA88",
      accentDark: "#609A42",
      text: "#2E4C2A",
      textSecondary: "#446C3E",
      button: "#6EB054",
      buttonText: "#FFFFFF",
    },
  },

  {
    id: 31,
    name: "Лотос",
    colors: {
      bg: "#DCE8E4",
      bgAlt: "#D0DCDA",
      card: "#E8F0EC",
      accent: "#66A08C",
      accentLight: "#9AC8B8",
      accentDark: "#4C8472",
      text: "#2A4A40",
      textSecondary: "#3E6A58",
      button: "#5C9A84",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 32,
    name: "Алоэ",
    colors: {
      bg: "#DEEAD8",
      bgAlt: "#D2DECC",
      card: "#EAF2E4",
      accent: "#6AA86E",
      accentLight: "#9ECCA0",
      accentDark: "#508C54",
      text: "#2A4C30",
      textSecondary: "#3E6C46",
      button: "#5EA266",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 33,
    name: "Эвкалипт",
    colors: {
      bg: "#DCE8E0",
      bgAlt: "#D0DCD8",
      card: "#E8F0EC",
      accent: "#649E88",
      accentLight: "#98C4B4",
      accentDark: "#4A826E",
      text: "#2A4A3E",
      textSecondary: "#3E6A56",
      button: "#5A9880",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 34,
    name: "Суккулент",
    colors: {
      bg: "#DEEADC",
      bgAlt: "#D2DEDA",
      card: "#EAF2E8",
      accent: "#68A47C",
      accentLight: "#9CCAAA",
      accentDark: "#4E8862",
      text: "#2A4A36",
      textSecondary: "#3E6A4A",
      button: "#5E9E74",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 35,
    name: "Авокадо",
    colors: {
      bg: "#E2ECDC",
      bgAlt: "#D6E0D0",
      card: "#EEF4E8",
      accent: "#70AA70",
      accentLight: "#A2CE9E",
      accentDark: "#568E56",
      text: "#2C4C30",
      textSecondary: "#426C46",
      button: "#64A468",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 36,
    name: "Нефрит",
    colors: {
      bg: "#DCE8DC",
      bgAlt: "#D0DCDA",
      card: "#E8F0E8",
      accent: "#5CA078",
      accentLight: "#90C6A6",
      accentDark: "#42845E",
      text: "#2A4A38",
      textSecondary: "#3E6A4C",
      button: "#529A70",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 37,
    name: "Малахит",
    colors: {
      bg: "#DAEAE0",
      bgAlt: "#CEDEDC",
      card: "#E6F2EC",
      accent: "#56A07E",
      accentLight: "#8AC8AC",
      accentDark: "#3C8464",
      text: "#284A3A",
      textSecondary: "#3C6A52",
      button: "#4C9A76",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 38,
    name: "Изумруд",
    colors: {
      bg: "#DAEADC",
      bgAlt: "#CEDEDC",
      card: "#E6F2E8",
      accent: "#58A47A",
      accentLight: "#8CCAAA",
      accentDark: "#3E8860",
      text: "#284A36",
      textSecondary: "#3C6A4E",
      button: "#4E9E72",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 39,
    name: "Хризолит",
    colors: {
      bg: "#E2ECDA",
      bgAlt: "#D6E0CE",
      card: "#EEF4E6",
      accent: "#6EAC68",
      accentLight: "#A0D094",
      accentDark: "#54904E",
      text: "#2C4C2C",
      textSecondary: "#426C42",
      button: "#62A65C",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 40,
    name: "Хризопраз",
    colors: {
      bg: "#DFF0DC",
      bgAlt: "#D3E4D0",
      card: "#ECF7E8",
      accent: "#68B070",
      accentLight: "#98D4A0",
      accentDark: "#4E9456",
      text: "#2A4C2E",
      textSecondary: "#3E6C44",
      button: "#5CAA68",
      buttonText: "#FFFFFF",
    },
  },

  {
    id: 41,
    name: "Серпентин",
    colors: {
      bg: "#DCEADC",
      bgAlt: "#D0DEDA",
      card: "#E8F2E8",
      accent: "#60A07A",
      accentLight: "#94C8A8",
      accentDark: "#468460",
      text: "#2A4A36",
      textSecondary: "#3E6A4C",
      button: "#569A72",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 42,
    name: "Амазонит",
    colors: {
      bg: "#DCE8E8",
      bgAlt: "#D0DCDC",
      card: "#E8F0F0",
      accent: "#5CA096",
      accentLight: "#90C6BE",
      accentDark: "#42847C",
      text: "#2A4A46",
      textSecondary: "#3E6A5E",
      button: "#529A8E",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 43,
    name: "Празем",
    colors: {
      bg: "#DCE8DA",
      bgAlt: "#D0DCCE",
      card: "#E8F0E6",
      accent: "#5E9E70",
      accentLight: "#92C69E",
      accentDark: "#448256",
      text: "#2A4A34",
      textSecondary: "#3E6A48",
      button: "#549868",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 44,
    name: "Мята",
    colors: {
      bg: "#DCF0EC",
      bgAlt: "#D0E4E0",
      card: "#E8F7F4",
      accent: "#60B49E",
      accentLight: "#94D8C6",
      accentDark: "#469884",
      text: "#2A4C44",
      textSecondary: "#3E6C5C",
      button: "#56AE96",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 45,
    name: "Морская пена",
    colors: {
      bg: "#DCF0EE",
      bgAlt: "#D0E4E2",
      card: "#E8F7F6",
      accent: "#5CB6A8",
      accentLight: "#8EDACE",
      accentDark: "#429A8E",
      text: "#2A4C48",
      textSecondary: "#3E6C60",
      button: "#52B0A0",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 46,
    name: "Бирюза",
    colors: {
      bg: "#DAEEF0",
      bgAlt: "#CEE2E4",
      card: "#E6F5F7",
      accent: "#58B8B0",
      accentLight: "#88DCDA",
      accentDark: "#3E9C96",
      text: "#2A4C4A",
      textSecondary: "#3E6C64",
      button: "#4EB2AA",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 47,
    name: "Аквамарин",
    colors: {
      bg: "#DCEEE8",
      bgAlt: "#D0E2DC",
      card: "#E8F5F0",
      accent: "#5CB4A0",
      accentLight: "#8ED8C8",
      accentDark: "#429886",
      text: "#2A4C42",
      textSecondary: "#3E6C5A",
      button: "#52AE98",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 48,
    name: "Ментол",
    colors: {
      bg: "#DCF0EC",
      bgAlt: "#D0E4E0",
      card: "#E8F7F4",
      accent: "#58B29C",
      accentLight: "#88D6C4",
      accentDark: "#3E9682",
      text: "#2A4C44",
      textSecondary: "#3E6C5C",
      button: "#4EAC94",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 49,
    name: "Ледяная мята",
    colors: {
      bg: "#DCEEF0",
      bgAlt: "#D0E2E4",
      card: "#E8F5F7",
      accent: "#5CB0AA",
      accentLight: "#8ED4CE",
      accentDark: "#429490",
      text: "#2A4C4A",
      textSecondary: "#3E6C62",
      button: "#52AAA2",
      buttonText: "#FFFFFF",
    },
  },
  {
    id: 50,
    name: "Мятный крем",
    colors: {
      bg: "#DCEEE8",
      bgAlt: "#D0E2DC",
      card: "#E8F5F0",
      accent: "#60B4A0",
      accentLight: "#92D8C8",
      accentDark: "#469886",
      text: "#2A4C42",
      textSecondary: "#3E6C5A",
      button: "#56AE98",
      buttonText: "#FFFFFF",
    },
  },
];

export function getPaletteById(id: number): Palette | undefined {
  return palettes.find((p) => p.id === id);
}
